### ISSUE TITLE
stimela build error: cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by rramij** [saopicc/DDFacet#13]
(stimelavenv) [ramij@localhost ~]$ stimela build
Running: docker build --force-rm -f /tmp/tmpdZ_Lav/tmpdA5sP3 -t ramij_cab/tigger_tag /tmp/tmpdZ_LavGot permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=tmpdA5sP3&forcerm=1&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=lt3rcogq5p9u3p8xc50yosvs5&shmsize=0&t=ramij_cab%2Ftigger_tag&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied

Traceback (most recent call last):
File "/home/ramij/stimelavenv/bin/stimela", line 14, in
main.main([a for a in sys.argv[1:]])
File "/home/ramij/stimelavenv/lib/python2.7/site-packages/stimela/main.py", line 640, in main
_cmd(argv)
File "/home/ramij/stimelavenv/lib/python2.7/site-packages/stimela/main.py", line 132, in build
build_args=build_args, args=no_cache)
File "/home/ramij/stimelavenv/lib/python2.7/site-packages/stimela/docker.py", line 42, in build
bdir])
File "/home/ramij/stimelavenv/lib/python2.7/site-packages/stimela/utils/init.py", line 172, in xrun
'%s: returns errr code %d' % (command, process.returncode))
stimela.utils.StimelaCabRuntimeError: docker build: returns errr code 1

I am in the docker group. I don't understand what's wrong.
(stimelavenv) [ramij@localhost ~]$ grep /etc/group -e "docker"
docker:x:983:ramij

**Comment by rramij** [comment]
The problem is resolved by "deactivate"-ing environment, exit terminal and re-activate.
