### ISSUE TITLE
TypeError: 'ItemLoadError' object is not subscriptable

### ISSUE THREAD

**Issue by samit97** [saopicc/DDFacet#44]
Hi,
I am trying to run ddfacet with simulated ska data. I am getting the following error : 

    Mapping BDA.Grid........87320/87320 [==================================================] 100%  - 1'27" 
Error loading file:///dev/shm/ddf.292851/DATA:0:0:BDA.Grid:tmp/str:blocks:d/str:194:205:a
Error loading item /dev/shm/ddf.292851/DATA:0:0:BDA.Grid:tmp/str:blocks:d/str:194:205:a
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Array/shared_dict.py", line 68, in load
    return self.load_impl()
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Array/shared_dict.py", line 76, in load_impl
    return NpShared.GiveArray(_to_shm(self.path))
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Array/NpShared.py", line 147, in GiveArray
    raise e
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Array/NpShared.py", line 136, in GiveArray
    return SharedArray.attach(Name)
OSError: [Errno 12] Cannot allocate memory: 'file:///dev/shm/ddf.292851/DATA:0:0:BDA.Grid:tmp/str:blocks:d/str:194:205:a'
 - 18:17:55 - AsyncProcessPool             [6.1/16.7 15.0/25.4 8.7Gb] process io00: exception raised processing job DATA:0:0: Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Other/AsyncProcessPool.py", line 870, in _dispatch_job
    result = call(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Data/ClassVisServer.py", line 612, in _handler_LoadVisChunk
    self.collectBDA(dictname, DATA)
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Data/ClassVisServer.py", line 630, in collectBDA
    FinalMapping, fact = self._smm_grid.collectSmearMapping(DATA, "BDA.Grid")
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Data/ClassSmearMapping.py", line 117, in collectSmearMapping
    FinalMapping[iii:iii+BlocksRowsListBL.size] = BlocksRowsListBL[:]
TypeError: 'ItemLoadError' object is not subscriptable

 - 18:17:55 - AsyncProcessPool             [0.2/0.4 12.7/12.7 8.7Gb] Reading 1.1: 1 jobs complete, average single-core time 129.20s per job
 - 18:17:55 - AsyncProcessPool             [0.2/0.4 12.7/12.7 8.7Gb] DATA:0:0: 1 jobs returned an error. Aborting.
DDFacet has encountered an unexpected error. Dropping you into pdb for a post-mortem.
(This is because you're running with --Debug-Pdb set to 'auto' and --Log-Boring is off.)
Traceback (most recent call last):
  File "/opt/venv/bin/DDF.py", line 461, in <module>
    main(OP, messages)
  File "/opt/venv/bin/DDF.py", line 295, in main
    Imager.main()
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Imager/ClassDeconvMachine.py", line 1126, in main
    self.GiveDirty(psf=True, sparsify=sparsify, last_cycle=(NMajor==0))
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Imager/ClassDeconvMachine.py", line 682, in GiveDirty
    DATA = self.VS.collectLoadedChunk(start_next=True)
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Data/ClassVisServer.py", line 496, in collectLoadedChunk
    APP.awaitJobResults(self._next_chunk_name, timing="Reading %s"%self._next_chunk_label )
  File "/opt/venv/lib/python3.8/site-packages/DDFacet/Other/AsyncProcessPool.py", line 761, in awaitJobResults
    raise RuntimeError("some distributed jobs have failed")
RuntimeError: some distributed jobs have failed

**Comment by mhardcastle** [comment]
The actual error here is "OSError: [Errno 12] Cannot allocate memory: 'file:///dev/shm/ddf.292851/DATA:0:0:BDA.Grid:tmp/str:blocks:d/str:194:205:a'". You  need to increase the available RAM or decrease DDFacet's RAM usage.
