### ISSUE TITLE
pybdsf version

### ISSUE THREAD

**Issue by mhardcastle** [saopicc/DDFacet#50]
Is there a reason for the upper limit on pybdsf version? I've removed it without apparent consequences, and not having it will assist in fixing pybdsf/DDF incompatibilities down the line.

**Comment by bennahugo** [comment]
Need to fix the changes that stem from the catalog file name changes for the clustering tooling. At least that is what I ran into last when I tried this.

**Comment by bennahugo** [comment]
Tracked down the original issue - need to change
```
--> Wrote FITS file 'TestLOFAR_J1329_p4729.run.app.restored.pybdsf.srl.fits'
--> Wrote FITS file 'TestLOFAR_J1329_p4729.run.app.restored.pybdsf.gaul.fits'
--> Wrote BBS sky model 'TestLOFAR_J1329_p4729.run.app.restored.pybdsf.sky_in'
--> Wrote file 'TestLOFAR_J1329_p4729.run.app.restored.pybdsf_rms.fits'
--> Wrote file 'TestLOFAR_J1329_p4729.run.app.restored.pybdsf_mean.fits'
 - 21:53:53 - ClusterImage                 | Reading /test_output/TestLOFAR_J1329_p4729.run.app.restored.pybdsm.srl.fits
Warning: setupterm: could not find terminfo database
Traceback (most recent call last):
  File "/opt/venv/bin/ClusterCat.py", line 340, in <module>
    main(options=options)
  File "/opt/venv/bin/ClusterCat.py", line 329, in main
    CIM=ClusterImage(**options.__dict__)
  File "/opt/venv/bin/ClusterCat.py", line 73, in __init__
    f=fits.open(self.SourceCat)
  File "/opt/venv/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 175, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache,
  File "/opt/venv/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 410, in fromfile
    return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
  File "/opt/venv/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 1060, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/opt/venv/lib/python3.8/site-packages/astropy/io/fits/file.py", line 170, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/opt/venv/lib/python3.8/site-packages/astropy/io/fits/file.py", line 562, in _open_filename
    self._file = open(self.name, IO_FITS_MODES[mode])
FileNotFoundError: [Errno 2] No such file or directory: '/test_output/TestLOFAR_J1329_p4729.run.app.restored.pybdsm.srl.fits'
```

in clustercat. cyriltasse/DDFacet#859

**Comment by bennahugo** [comment]
I've put in an upgrade to bdsf 1.11.1 and fixes to work with the change in suffixes. If it works I will try upgrade numpy to 1.26.4

**Comment by bennahugo** [comment]
Alright it is in the dev repo's master @mhardcastle. In the end I've opted to keep numpy pinned to 1.22.4 due to what seems to be a performance regression in later numpy and upgrade bdsf to the latest.
