### ISSUE TITLE
No output image cube

### ISSUE THREAD

**Issue by Athanaseus** [saopicc/DDFacet#7]
I'm running the [latest](https://github.com/saopicc/DDFacet/releases/tag/0.3.4.1) ddfacet via [stimela](https://github.com/SpheMakh/Stimela) and specifying my output cubes as a combination of `MmRrIi`.

This a list of all output:
```
meerkat_SourceRecovery_ddfacet.alpha.fits
meerkat_SourceRecovery_ddfacet.app.convmodel.fits
meerkat_SourceRecovery_ddfacet.app.model.fits
meerkat_SourceRecovery_ddfacet.app.residual.fits
meerkat_SourceRecovery_ddfacet.app.restored.fits
meerkat_SourceRecovery_ddfacet.cube.app.model.fits
meerkat_SourceRecovery_ddfacet.cube.app.residual.fits
meerkat_SourceRecovery_ddfacet.dirty.corr.fits
meerkat_SourceRecovery_ddfacet.dirty.fits
meerkat_SourceRecovery_ddfacet.model01.fits
meerkat_SourceRecovery_ddfacet.model02.fits
meerkat_SourceRecovery_ddfacet.NormFacets.fits
meerkat_SourceRecovery_ddfacet.Norm.fits
meerkat_SourceRecovery_ddfacet.psf.fits
meerkat_SourceRecovery_ddfacet.residual01.fits
meerkat_SourceRecovery_ddfacet.residual02.fits
meerkat_SourceRecovery_ddfacet.restored.fits
```

I'm missing the **restored** image cube!

**Comment by Athanaseus** [comment]
Here is part of the log:
```
 - 11:20:54 - ClassCasaImage            |   ----> Save image data as FITS file /home/ramaila/output/meerkat_SourceRecovery_ddfacet.model02.fits
 - 11:29:59 - AsyncProcessPool          | Degrid 1.1: 1 jobs complete, average single-core time 544.38s per job
 - 11:30:02 - AsyncProcessPool          | Grid 1.1: 1 jobs complete, average single-core time 2.75s per job
 - 11:30:02 - ClassImagerDeconv         | no more data: EndOfObservation
 - 11:30:25 - AsyncProcessPool          | FFT: 1 jobs complete, average single-core time 22.65s per job
 - 11:30:47 - AsyncProcessPool          | Mean per-facet dirties: 1 jobs complete, average single-core time 21.98s per job
 - 11:30:47 - ClassFacetMachine         | Combining facets to stitched Dirty image
Error.  nthreads must be a positive integer - 11:30:56 - ClassCasaImage            |   ----> Save image data as FITS file /home/ramaila/output/meerkat_SourceRecovery_ddfacet.residual02.fits
 - 11:30:56 - ClassModelMachineMSMF     | Saving dico model to /home/ramaila/output/meerkat_SourceRecovery_ddfacet.DicoModel
 - 11:30:57 - ClassImagerDeconv         | Saving last residual image to /home/ramaila/msdir/meerkat_SourceRecovery.ms.F0.D0.ddfcache/LastResidual
 - 11:31:01 - ClassImagerDeconv         | Saving last residual image to /home/ramaila/msdir/meerkat_SourceRecovery.ms.F0.D0.ddfcache/LastResidual
 - 11:31:04 - ClassImagerDeconv         | Create restored image
 - 11:31:04 - ClassCasaImage            | [io00]   ----> Save image data as FITS file /home/ramaila/output/meerkat_SourceRecovery_ddfacet.app.residual.fits
 - 11:31:06 - ClassCasaImage            | [io00]   ----> Save image data as FITS file /home/ramaila/output/meerkat_SourceRecovery_ddfacet.app.model.fits
 - 11:31:17 - ClassCasaImage            | [io00]   ----> Save image data as FITS file /home/ramaila/output/meerkat_SourceRecovery_ddfacet.app.convmodel.fits
 - 11:31:18 - ClassCasaImage            | [io00]   ----> Save image data as FITS file /home/ramaila/output/meerkat_SourceRecovery_ddfacet.app.restored.fits
 - 11:31:18 - ClassCasaImage            | [io00]   ----> Save image data as FITS file /home/ramaila/output/meerkat_SourceRecovery_ddfacet.restored.fits
 - 11:31:53 - ClassModelMachineMSMF     | computing alpha map for model pixels above 2.1e-09 Jy (based on max DR setting of 1e+06)
 - 11:31:55 - ClassCasaImage            | [io00]   ----> Save image data as FITS file /home/ramaila/output/meerkat_SourceRecovery_ddfacet.alpha.fits
 - 11:32:03 - ClassCasaImage            | [io00]   ----> Save image data as FITS file /home/ramaila/output/meerkat_SourceRecovery_ddfacet.cube.app.model.fits
 - 11:32:05 - ClassCasaImage            | [io00]   ----> Save image data as FITS file /home/ramaila/output/meerkat_SourceRecovery_ddfacet.cube.app.residual.fits
 - 11:32:15 - AsyncProcessPool          | [comp12] process comp12: exception raised processing job convolve:intmodelcube:intconvmodelcube:2: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Other/AsyncProcessPool.py", line 844, in _dispatch_job
    result = handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/ToolsDir/ModFFTW.py", line 521, in _convolveSingleGaussianFFTW_noret
    _convolveSingleGaussianFFTW(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/ToolsDir/ModFFTW.py", line 397, in _convolveSingleGaussianFFTW
    Ain = shareddict[field_in][ch]
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Array/shared_dict.py", line 192, in __getitem__
    value = collections.OrderedDict.__getitem__(self, item)
KeyError: 'intmodelcube'

 - 11:32:15 - AsyncProcessPool          | [comp20] process comp20: exception raised processing job convolve:intmodelcube:intconvmodelcube:1: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Other/AsyncProcessPool.py", line 844, in _dispatch_job
    result = handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/ToolsDir/ModFFTW.py", line 521, in _convolveSingleGaussianFFTW_noret
    _convolveSingleGaussianFFTW(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/ToolsDir/ModFFTW.py", line 397, in _convolveSingleGaussianFFTW
    Ain = shareddict[field_in][ch]
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Array/shared_dict.py", line 192, in __getitem__
    value = collections.OrderedDict.__getitem__(self, item)
KeyError: 'intmodelcube'

 - 11:32:15 - AsyncProcessPool          | [comp12] process comp12: exception raised processing job convolve:intmodelcube:intconvmodelcube:3: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Other/AsyncProcessPool.py", line 844, in _dispatch_job
    result = handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/ToolsDir/ModFFTW.py", line 521, in _convolveSingleGaussianFFTW_noret
    _convolveSingleGaussianFFTW(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/ToolsDir/ModFFTW.py", line 397, in _convolveSingleGaussianFFTW
    Ain = shareddict[field_in][ch]
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Array/shared_dict.py", line 192, in __getitem__
    value = collections.OrderedDict.__getitem__(self, item)
KeyError: 'intmodelcube'

 - 11:32:15 - AsyncProcessPool          | [comp10] process comp10: exception raised processing job convolve:intmodelcube:intconvmodelcube:0: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Other/AsyncProcessPool.py", line 844, in _dispatch_job
    result = handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/ToolsDir/ModFFTW.py", line 521, in _convolveSingleGaussianFFTW_noret
    _convolveSingleGaussianFFTW(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/ToolsDir/ModFFTW.py", line 397, in _convolveSingleGaussianFFTW
    Ain = shareddict[field_in][ch]
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Array/shared_dict.py", line 192, in __getitem__
    value = collections.OrderedDict.__getitem__(self, item)
KeyError: 'intmodelcube'

 - 11:32:15 - AsyncProcessPool          | convolve:intmodelcube:intconvmodelcube:*: 4 jobs returned an error. Aborting.
 - 11:32:15 - DDFacet                   | Traceback (most recent call last):
  File "/usr/local/bin/DDF.py", line 372, in <module>
    main(OP, messages)
  File "/usr/local/bin/DDF.py", line 221, in main
    Imager.main()
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Imager/ClassDeconvMachine.py", line 1334, in main
    self.Restore()
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Imager/ClassDeconvMachine.py", line 2186, in Restore
    a, b = apprescube(), appconvmodelcube()
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Imager/ClassDeconvMachine.py", line 1929, in appconvmodelcube
    _images[label] = intconvmodelcube()
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Imager/ClassDeconvMachine.py", line 1942, in intconvmodelcube
    CellSizeRad=self.CellSizeRad, GaussPars=self.PSFGaussPars)
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/ToolsDir/ModFFTW.py", line 514, in ConvolveGaussianParallel
    APP.awaitJobResults(jobid+"*") #, progress="Convolving")
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Other/AsyncProcessPool.py", line 741, in awaitJobResults
    raise RuntimeError("some distributed jobs have failed")
RuntimeError: some distributed jobs have failed

 - 11:32:15 - DDFacet                   | 
 - 11:32:15 - DDFacet                   | There was a problem after 31m48.9s; if you think this is a bug please open an issue, 
 - 11:32:15 - DDFacet                   |   quote your version of DDFacet and attach your logfile.
 - 11:32:15 - DDFacet                   | You are using DDFacet revision: 0.3.4.1
 - 11:32:15 - DDFacet                   | Your logfile is available here: /home/ramaila/output/meerkat_SourceRecovery_ddfacet.log
Traceback (most recent call last):
  File "/usr/local/bin/DDF.py", line 415, in <module>
    APP.shutdown()
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Other/AsyncProcessPool.py", line 766, in shutdown
    self.restartWorkers()
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Other/AsyncProcessPool.py", line 379, in restartWorkers
    raise WorkerProcessError()
DDFacet.Other.AsyncProcessPool.WorkerProcessError
Traceback (most recent call last):
  File "/scratch/code/run.py", line 35, in <module>
    utils.xrun(cab['binary'], args)
  File "/scratch/stimela/utils/__init__.py", line 73, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
SystemError: DDF.py: returns errr code 1
```

**Comment by bennahugo** [comment]
Fixed upstream @Athanaseus please retest

**Comment by Athanaseus** [comment]
Thanks @bennahugo.
@bennahugo or @cyriltasse please add me to the private repo, I do not have access.
